### ISSUE TITLE
Robot model might "seperate" 

### ISSUE THREAD

**Issue by Red-edge** [ChangeClock/RobomasterSimulator#32]
The armor model of robot may displace when undergo hitting event( ammo hitting, crashing into wall etc.).

> Failed at attempts of screenshot

**Comment by Red-edge** [comment]
## Oh i got a freaking good example
This is how i **died** once! An armor in wall!
Oh also failed initial revival display example.
![image](https://github.com/ChangeClock/RobomasterSimulator/assets/118868872/4a568fb8-014f-4708-bbf0-a7fd67c2f033)

**Comment by ChangeClock** [comment]
This requires a big change in armor prefabs, as it's attached to other objects like the chassis through the fixed joint. But fixed joint is not literally 'fixed' in the physical engine due to its limitation. Combining the armor and chassis together should avoid this problem, but it will break the current design and the armor cannot work on itself. The reason is that collision detection can only be detected on the chassis object (parent object) and the armor itself cannot handle it independently.

Will figure out a solution later.
